WebEduardov2/WebEduardo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include ("web.urls")),
    path('nombres/', include ("nombres.urls")) 
]

WebEduardov2/nombres/urls.py
from django.urls import path
from . import views

app_name = "nombres"

urlpatterns = [
	path("",views.index, name="index"),
	path("add", views.add, name="add")
]

WebEduardov2/web/urls.py
from django.urls import path, include
from . import views

app_name = "web"

urlpatterns = [
        path("", views.index, name="index"),
        path('index.html', views.index, name="index"),
        path("quiensomos.html", views.quiensomos_view, name="quiensomos.html"),
        path("servicios.html", views.servicios_view, name="servicios.html"),
        path("clientes.html", views.clientes_view, name="clientes.html"),
        path("noticia1.html", views.noticia1_view, name="noticia1.html"),
        path("noticia2.html", views.noticia2_view, name="noticia2.html"),
        path("noticia3.html", views.noticia3_view, name="noticia3.html"),
        path('accounts/', include('django.contrib.auth.urls'))
]

WebEduardov2/nombres/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django import forms

# Create your views here.

class FormularioUsuario (forms.Form):
	nombres = forms.CharField(label="Nuevo usuario")
	rango = forms.IntegerField(label="Registrarse como:")

def index(request):
	
	if "listaUsuarios" not in request.session:
		request.session["listaUsuarios"] = []
	return render(request, "nombres/index.html", {
		"nombres": request.session["listaUsuarios"]
	})

def add(request):
	if request.method == "POST":
		formulario = Formulariousuario(request.POST)
		if formulario.is_valid():
			tarea = formulario.cleaned_data["nombres"]
			request.session["listaUsuarios"] += [tarea]
			return HttpResponseRedirect(reverse("nombres:index"))
		else:
			return render(request, "nombres/add.html", {
				"form": formulario
			})
	else:
		return render(request, "nombres/add.html", {
			"form":FormularioUsuario()
		})

WebEduardov2/web/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django import forms

# Create your views here

def index(request):
	return render(request, "web/index.html")

def quiensomos_view(request):
	return render(request, "web/quiensomos.html")

def servicios_view(request):
	return render(request, "web/servicios.html")

def clientes_view(request):
	return render(request, "web/clientes.html")

def noticia1_view(request):
	return render(request, "web/noticia1.html")

def noticia2_view(request):
	return render(request, "web/noticia2.html")

def noticia3_view(request):
	return render(request, "web/noticia3.html")

WebEduardov2/nombres/templates/nombres/add.html
{% extends "nombres/layout.html" %}

{% block body %}
		<h1> Añadir usuario: </h1>
		<form action="{% url 'nombres:add' %}" method="post">
		{% csrf_token %}
		{{ form }}
			<input type="submit">
		</form>
		<a href="{% url 'nombres:index' %}"> Ver usuarios </a>
{% endblock %}

WebEduardov2/nombres/templates/nombres/clientes.html
<!DOCTYPE html>
<html lang="es">
	<head>		
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
            	<title>Formulario</title>
				<link rel="stylesheet" href="estilo.css">
	</head>

	<body> 

		
		<h1 style="text-align: center;">ACCEDER A LA PÁGINA WEB (EN DESARROLLO)</style></h1>
		<form style="text-align: center;">
			<input style="text-align: center;" type="text" placeholder="Nombre" name="nombre">
			<input style="text-align: center;" type="password" placeholder="Contraseña" name="contraseña">
			<div>
				<strong>Entrar como:</strong>
				<input name="modo" type="radio" value="usuario">Cliente
				<input name="modo" type="radio" value="administrador">Administrador
				<input name="modo" type="radio" value="usuario">Trabajador
				<p style="text-align: center;"><strong>Link GitHub</strong></p>
		</form>
		<p><img src="imagenes/git.png" alt="description" width="100" height="48" /></p>
	</body>
</html>

WebEduardov2/nombres/templates/nombres/layout.html
<!DOCTYPE html>
<html lang="es">
        <head>
                <title> Accede a tu cuenta </title>
        </head>
        <body>
         {% block body %}
         {% endblock %}
        </body>
</html>

WebEduardov2/web/templates/web/clientes.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>HuescaTelecom</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <div id="linea"></div> 
    <div id="header">
        <div id="centro1">
            <div id="logo">
                <h2>HuescaTelecom</h2>
                <p>Servicios de telecomunicaciones</p>
            </div>

            <div id="menu">
                <ul>
                    <li><a href="index.html">Inicio</a></li>
                    <li><a href="quiensomos.html">Quien somos</a></li>
                    <li><a href="servicios.html">Servicios</a></li>
                    <li><a href="https://www.movistar.es/Privada/DesafioUnico/">Movistar</a></li>
                    <li><a href="clientes.html">Acceso clientes</a></li>
                </ul>
            </div>
        </div>
    </div>

	<body> 	
		<h1 style="text-align: center;">ACCEDER A LA PÁGINA WEB (EN DESARROLLO)</style></h1>
		<form style="text-align: center;">
			<input style="text-align: center;" type="text" placeholder="Nombre" name="nombre">
			<input style="text-align: center;" type="password" placeholder="Contraseña" name="contraseña">
			<div>
				<strong>Entrar como:</strong>
				<input name="modo" type="radio" value="usuario">Cliente
				<input name="modo" type="radio" value="administrador">Administrador
				<input name="modo" type="radio" value="usuario">Trabajador
				<p style="text-align: center;"><strong>Link GitHub</strong></p>
		</form>
		<p><img src="imagenes/git.png" alt="description" width="100" height="48" /></p>
	</body>
</html>

WebEduardov2/web/templates/web/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>HuescaTelecom</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <div id="linea"></div> 
    <div id="header">
        <div id="centro1">
            <div id="logo">
                <h2>HuescaTelecom</h2>
                <p>Servicios de telecomunicaciones</p>
            </div>

            <div id="menu">
                <ul>
                    <li><a href="index.html">Inicio</a></li>
                    <li><a href="quiensomos.html">Quien somos</a></li>
                    <li><a href="servicios.html">Servicios</a></li>
                    <li><a href="https://www.movistar.es/Privada/DesafioUnico/">Movistar</a></li>
                    <li><a href="clientes.html">Acceso clientes</a></li>
                </ul>
            </div>
        </div>
    </div><!--termina el header-->

    <div id="presentacion">
        <div id="centro2">
            <div id="izquierda">
                <h2>Soluciones tecnológicas desde 1980</h2>
                <p class="descripcion-pres">Especialistas en despliegue y mantenimiento 
                de instlaciones de telecomunicaciones</p>
                <button class="boton">Más información aquí</button>
            </div>
            <div id="derecha">
                <img src="{% static 'web/descripcion.png' %}" class="img1">
            </div>
        </div>

    <div id="contenidos">
        <div id="centro3">
            <div id="izquierda">
                <h3>¿Quién somos?</h3>
                <p class="descripcion">
                    En HuescaTelecom ofrecemos soluciones tecnológicas
                    para nuestros clientes, tanto particulares como empresas.
                    <br> <br>
                    Desde 1980, somos pioneros en instalaciones de telecomunicaciones 
                    en la provincia de Huesca.
                </p>    
                <div id="imagenes">
                    <img src="{% static 'web/repetidor.png' %}" class="img-servicios">
                    <img src="{% static 'web/repetidor2.jpg' %}" class="img-servicios">
                    <img src="{% static 'web/repetidor3.jpg' %}" class="img-servicios">
                </div>
            </div>  
            <div id="derecha">
                <h3>Últimas novedades</h3>

                    En esta sección ofrecemos noticias actuales relacionadas 
                    con la tecnología
                </p>
                <article>
                    <h4>Se queda dormido al volante de un Tesla provocando una peculiar persecución policial</h4>
                    <p>
                        Quedarse dormido al volante le ha costado a esta persona su permiso de conducir y, además, que la policía tenga que perseguirle durante 15 minutos.
                    </p>
                    <a href="noticia1.html" class="leer-mas">Leer más</a>
                </article>
                <article>
                    <h4>Espiar desde el cielo: así funciona la tecnología de los globos estratosféricos</h4>
                    <p>
                        Estados Unidos rastrea un presunto artefacto espía chino que vuela sobre su territorio
                    </p>
                    <a href="noticia2.html" class="leer-mas">Leer más</a>
                </article>
                <article>
                    <h4>Día de Internet Seguro: ¿puede sufrir España un ciberataque como el de Italia?</h4>
                    <p>
                        Mientras nuestros vecinos transalpinos siguen azotados por un ataque ransomware a gran escala, las ciberdefensas españolas no paran de ascender en la clasificación de ‘players’ mundiales. Pero, no se confíe, los hackers tienen cada vez más comodines para hacerle caer en sus garras. Las pérdidas económicas por ciberdelincuencia aumentan exponencialmente y ya ni siquiera hace falta saber informática para lanzar un ataque.
                    </p>
                    <a href="noticia3.html" class="leer-mas">Leer más</a>
                </article>

            </div> 
        </div>
    </div>

    <div id="pie">
        <div id=centro-pie>
            <p>
                (c)Todos los derechos reservados. Diseñado por 
                <a href="https://github.com/EduardoVillacampa/eduardo.github.io" class="github"> Eduardo Villacampa</a>
            </p>
        </div>
    </div>
</body>
</html>

WebEduardov2/web/templates/web/noticia1.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>HuescaTelecom</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <div id="linea"></div> 
    <div id="header">
        <div id="centro1">
            <div id="logo">
                <h2>HuescaTelecom</h2>
                <p>Servicios de telecomunicaciones</p>
            </div>

            <div id="menu">
                <ul>
                    <li><a href="index.html">Inicio</a></li>
                    <li><a href="quiensomos.html">Quien somos</a></li>
                    <li><a href="servicios.html">Servicios</a></li>
                    <li><a href="https://www.movistar.es/Privada/DesafioUnico/">Movistar</a></li>
                    <li><a href="clientes.html">Acceso clientes</a></li>
                </ul>
            </div>
        </div>
    </div><!--termina el header-->


    <div id="contenidos-paginas">
        <div id="centro3">
            <h2>
                Se queda dormido al volante de un Tesla provocando una peculiar persecución policial
            </h2>
            <p>
                <img src="{% static 'web/tesla.jpg' %}" class="img.quiensomos">
            </p>
            <p class="text-justify">
                Los coches eléctricos se han convertido en los vehículos del futuro o, al menos, 
                eso es lo que piensan muchas personas. Tal es la confianza de algunos usuarios
                 por este tipo de vehículos que, incluso, ponen en peligro su integridad física 
                 dentro de estos vehículos. Lo último que se ha visto es una persecución digna de una comedia.
                <br> <br>
                Esta historia tiene lugar en Alemania y cuenta como protagonista a un usuario con un vehículo Tesla en su posesión. 
                El día 29 de diciembre del año 2022 en una autopista alemana saliendo de Bamberg y con destino a Bayreuth ocurrió un suceso que todavía tiene impactados a los agentes de policía de Alemania.
                <br> <br>
                Lo que presenciaron los oficiales fue un vehículo Tesla que transitaba a cierta velocidad y por esta autopista. No iba ni demasiado deprisa, ni demasiado lento y esto suscitó ciertas sospechas por lo que decidieron darle el alto al vehículo con la sorpresa de que el Tesla seguía manteniendo su ruta y velocidad.
                <br> <br>
                Esta persecución tuvo una duración de quince minutos en la cual el coche de los oficiales seguía a este Tesla de forma constante, pero a una distancia prudente. Al ver que la situación se mantenía constante lo que hicieron los oficiales fue ponerse a la misma altura que el vehículo para comprobar qué era lo que estaba ocurriendo en el habitáculo.
                <br> <br>
                <b> Esta persona en un Tesla ha protagonizado una escena digna de una comedia </b>
                <br> <br>
                Al colocarse a la misma altura lo que han podido ver es que la persona, supuestamente al volante, era un varón de 45 años que se encontraba complemente dormido. No es que se hubiese quedado dormido por accidente, si no que todo indica que lo habría hecho de forma completamente premeditada.
                <br> <br>
                Y, es que, la posición del asiento completamente reclinada como las manos cruzadas fuera del volante indicarían que habría tomado la decisión de hacer que el Tesla le llevase hasta la ciudad mientras él dormía. ¿Cuál es el problema de esto? En Alemania el piloto automático de los coches eléctricos de Tesla no está permitido.
                <br> <br>
                Teniendo en cuenta que no está permitido lo que ha ocurrido finalmente es que se le ha retirado el permiso de conducir cuando, por fin, ha despertado y ha acatado las ordenes de estacionarse en un lugar de la autopista. Eso sí, lo peor de todo es que este conductor habría colocado un peso en el volante para engañar al sistema de conducción del Tesla.  
                
            </p>
    
            
             
        </div>
    </div>
    
    <div id="pie">
        <div id=centro-pie>
            <p>
                (c)Todos los derechos reservados. Diseñado por 
                <a href="https://github.com/EduardoVillacampa/eduardo.github.io" class="github"> Eduardo Villacampa</a>
            </p>
        </div>
    </div>
</body>
</html>

WebEduardov2/web/templates/web/noticia2.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>HuescaTelecom</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <div id="linea"></div> 
    <div id="header">
        <div id="centro1">
            <div id="logo">
                <h2>HuescaTelecom</h2>
                <p>Servicios de telecomunicaciones</p>
            </div>

            <div id="menu">
                <ul>
                    <li><a href="index.html">Inicio</a></li>
                    <li><a href="quiensomos.html">Quien somos</a></li>
                    <li><a href="servicios.html">Servicios</a></li>
                    <li><a href="https://www.movistar.es/Privada/DesafioUnico/">Movistar</a></li>
                    <li><a href="clientes.html">Acceso clientes</a></li>
                </ul>
            </div>
        </div>
    </div><!--termina el header-->


    <div id="contenidos-paginas">
        <div id="centro3">
            <h2>
                Espiar desde el cielo: así funciona la tecnología de los globos estratosféricos
            </h2>
            <p>
                <h3>Estados Unidos rastrea un presunto artefacto espía chino que vuela sobre su territorio</h3>
            </p>
            <p>
                <img src="{% static 'web/450_1000.jpeg' %}" class="img.quiensomos">
            </p>
            <p class="text-justify">
                Estados Unidos ha detectado en los últimos días lo que parece ser un globo espía chino sobrevolando sus cielos en el Estado de Montana, junto a la frontera canadiense, según han confirmado mandos militares. “Ejemplos de este tipo de actividad de globos se han observado previamente en los últimos años”, indica en un comunicado el portavoz del Pentágono, Pat Ryder. Mientras que a veces se usan para estudiar el cosmos o confeccionar pronósticos meteorológicos, también hay quienes pretenden utilizarlos como un arma de espionaje.
                <br> <br>
                El globo detectado por Estados Unidos “viaja a una altitud muy por encima del tráfico aéreo comercial y no representa una amenaza militar o física para las personas en tierra”. Con esta descripción, podría tratarse de un globo estratosférico. O como lo define la Agencia Espacial Canadiense (ASC, por sus siglas en inglés), un globo de gran altitud que se lanza a la estratosfera. “Son el único tipo de globos que pueden operar en esta región de la atmósfera (de 15 a 45 kilómetros de altitud), que es demasiado baja para los satélites, demasiado alta para los aviones y demasiado rápida para los cohetes”, señala.
                <br> <br>
                Estos globos, según el organismo, suelen ser de plástico ultrafino relleno de helio y pueden estirarse en forma de una gigantesca lágrima invertida con una altura similar a la de la Torre Eiffel. Normalmente, están equipados con góndolas (canastas que penden del globo), que pueden transportar herramientas científicas, astronómicas o de predicción meteorológica, además de cámaras diurnas y térmicas, radares o incluso enjambres de drones.
                <br> <br>
                “Los globos estratosféricos son una plataforma elegida por científicos e ingenieros, ya que pueden usarse para probar y hacer avanzar la ciencia espacial por mucho menos que el coste de un satélite (hasta 40 veces menos) y brindan la oportunidad de llevar a cabo experimentos científicos concretos en un corto período de tiempo y obtener resultados rápidamente”, señala la ACS.
                <br> <br>
                <b>Espiar desde las alturas</b>
                <br> <br>
                Además de que sirven para realizar experimentos científicos en un entorno similar al espacio, estos globos pueden resultar útiles para monitorizar desastres naturales y en misiones de vigilancia. De hecho, un mando militar en el Pentágono ha confirmado, en declaraciones a la prensa y bajo anonimato, que el propósito del globo detectado por Estados Unidos “es claramente el espionaje”.
                <br> <br>
                Si bien en el pasado se han producido incidentes similares, en este caso resulta llamativo el tiempo que el globo ha permanecido en territorio estadounidense, más que en otras situaciones previas, según el mando militar. Como indica la ACS, los globos estratosféricos no requieren motor ni combustible y, en algunos casos, pueden realizar vuelos de larga duración: “De días, semanas e incluso meses”.
                <br> <br>
                Por ejemplo, World View Enterprises, una empresa con sede en Arizona que desarrolla tecnología para agencias gubernamentales y la NASA, consiguió en 2019 que uno de sus globos permaneciese en el aire durante 32 días. “Nuestros globos estratosféricos vuelan cinco veces más cerca de la Tierra que los satélites, proporcionando imágenes mucho más detalladas y posibilidades de recopilación de datos”, comentan sus creadores, que aseguran que esta información puede ser útil en la investigación marítima y gubernamental.
                <br> <br>
                El Gobierno de Estados Unidos ya ha tomado medidas para impedir que el aparato pueda recolectar información sensible, según cuenta Ryder. Mientras tanto, Mao Ning, portavoz del Ministerio de Exteriores chino, ha explicado que está verificando la información de Washington y ha instado a la prudencia. “Hacer conjeturas y elevar el tono antes de establecer los hechos no ayuda a la resolución apropiada del expediente”, ha afirmado.
                <br> <br>
                <b>Precio asequible</b>
                <br> <br>
                En los últimos años, varias potencias han experimentado hasta qué punto este tipo de globos pueden servir para vigilar una zona a un precio asequible. El Comité de Servicios Armados del Senado de Estados Unidos reconoció en 2020 “la creciente importancia de los globos estratosféricos en las misiones de mando, control, comunicaciones, informática, inteligencia, vigilancia y reconocimiento y defensa antimisiles”.
                <br> <br>
                El propio Departamento de Defensa de Estados Unidos invierte en este tipo de aparatos. En los últimos dos años, el Pentágono ha gastado alrededor de 3,8 millones de dólares (3,5 millones de euros) en proyectos de globos y planea gastar 27,1 millones en el año fiscal 2023 “para continuar trabajando en múltiples esfuerzos”, según documentos presupuestarios citados por el portal Politico.
                <br> <br>
                Mientras que algunos de sus programas buscan la forma de detectar e incluso derribar este tipo de globos, otros aspiran a crear los suyos propios para que puedan acechar en el espacio aéreo enemigo sin ser detectados. Así lo indica la revista estadounidense Popular Mechanics, citando el programa clasificado COLD STAR (Covert Long-Dwell Stratospheric Architecture), cuyo objetivo sería crear un globo equipado con sensores de alta fidelidad, sistemas de navegación autónoma e inteligencia artificial.
                <br> <br>
            
            
            
            
            </p>
    
            
             
        </div>
    </div>
    
    <div id="pie">
        <div id=centro-pie>
            <p>
                (c)Todos los derechos reservados. Diseñado por 
                <a href="https://github.com/EduardoVillacampa/eduardo.github.io" class="github"> Eduardo Villacampa</a>
            </p>
        </div>
    </div>
</body>
</html>

WebEduardov2/web/templates/web/noticia3.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>HuescaTelecom</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <div id="linea"></div> 
    <div id="header">
        <div id="centro1">
            <div id="logo">
                <h2>HuescaTelecom</h2>
                <p>Servicios de telecomunicaciones</p>
            </div>

            <div id="menu">
                <ul>
                    <li><a href="index.html">Inicio</a></li>
                    <li><a href="quiensomos.html">Quien somos</a></li>
                    <li><a href="servicios.html">Servicios</a></li>
                    <li><a href="https://www.movistar.es/Privada/DesafioUnico/">Movistar</a></li>
                    <li><a href="clientes.html">Acceso clientes</a></li>
                </ul>
            </div>
        </div>
    </div><!--termina el header-->


    <div id="contenidos-paginas">
        <div id="centro3">
            <h2>
               Día de Internet Seguro: ¿puede sufrir España un ciberataque como el de Italia?
            </h2>
            <p>
                <img src="{% static 'web/not3.jpg' %}" class="img.quiensomos">
            </p>
            <p class="text-justify">
                A veces toca resignarse. Las cartas que nos han repartido en el juego de la vida nos obligan a cosas como aprender a convivir con un virus que ya ha matado a casi 7 millones de personas en todo el mundo y a navegar por un universo digital en el que el mal acecha en cada esquina. Afortunadamente, para aquellos que no estén dispuestos a vivir aislados entre cuatro paredes analógicas y quieran seguir jugando, la baraja de nuestro día a día incluye varios comodines que, como las vacunas, nos protegen parcialmente de las infecciones informáticas.
                <br> <br>
                A nivel usuario, la mano ganadora es la del principio de precaución. Nunca pinche un enlace si no está seguro de que es auténtico. Nunca comparta sus datos personales si no tiene la certeza de quién es su interlocutor. Actualice sus sistemas que siempre el fabricante se lo requiera. Y, sobre todo, nunca peque de ingenuo, porque el peligro siempre está ahí, como demuestra el hecho de que, mientras celebramos el Día Internacional de Internet Seguro, Italia sigue sumida en un ataque ransomware a gran escala, cuyo impacto se ha expandido incluso por EEUU, Francia, Finlandia y Canadá.
                <br> <br>
                Los ciberdelincuentes saben que hay mucho dinero en el bote. En 2018 y tras un crecimiento exponencial desde 2001, las pérdidas económicas por ciberataques rozaron los 3.000 millones de dólares a nivel global, según el Foro Económico Mundial. Solo tres años después, en 2021, los costes ya se acercaban a los 7.000 millones de dólares, según el FBI. De acuerdo con esta tendencia, Cybercrime Magazine calcula que para 2025 la cifra podría ascender a los 10.500 billones de dólares en 2025. Si esto sucede, los daños causados por los ciberdelincuentes se alzarían como la tercera economía del mundo, solo por detrás de los PIB de EEUU y China.
                <br> <br>
                Por eso no es de extrañar que prácticamente no haya día en el que alguien no caiga en uno de sus órdagos: lo hemos visto en Ucrania, en el Instituto Nacional de Salud de Reino Unido y hasta en el propio Gobierno de España. La lista de víctimas es casi tan interminable como la de sus estrategias para hacernos picar. De hecho, aunque los casos más mediáticos se deban a sofisticadas herramientas como el software de espionaje Pegasus y a bandas criminales organizadas como Conti, en realidad ya ni siquiera hace falta ser experto en informática para sembrar el caos digital.
                <br> <br>
                Además de los servicios de hackeo profesional que se ofertan en la Internet profunda cual anuncios de fontanería, la inteligencia artificial (IA) ha eliminado la apuesta mínima para empezar jugar gracias a las herramientas automatizadas, que permiten a cualquiera lanzar sus propios ataques. Si las IA generativas han democratizado la creación de ilustraciones, los lucrativos hackeos no iban a quedarse atrás. Y la cosa va a peor, como demuestra el hecho de que las estafas informáticas hayan crecido un 455% en los últimos 6 años en nuestro país.
                <br> <br>
                Aunque, por supuesto, no somos la excepción. Mire la tabla que mire, “en el mundo de la ciberseguridad hay algo seguro: que los hackeos siempre van a más”, afirma el análisis del panorama cibernético para 2023 de MIT Technology Review. La única buena noticia es que España lleva años aprendiéndose las reglas del juego y poco a poco ha ido convirtiéndose en uno de los principales players en ciberseguridad a nivel mundial.
                <br> <br>
                Aquí no vamos de farol. A pesar de que en 2021 casi el 95% de las empresas españolas sufrieron un incidente informático de carácter grave , según Deloitte, en solo cinco años nuestra industria de la seguridad digital ha pasado de estar por detrás de países como Hungría a convertirse en el segundo miembro de la UE en cuanto a madurez, según el último Índice Global de Ciberseguridad de la Unión Internacional de las Telecomunicaciones.
                <br> <br>
                El cibercordero español se ha convertido en un lobo cuya ferocidad ya es reconocida incluso por expertos internacionales. “España es un centro de enorme importancia para nosotros en términos de ciberseguridad”, nos dijo hace poco la directora global de Talento y Sostenibilidad de Siemens, Judith Wiese. No en vano, aunque en 2022 el número de ciberprofesionales de nuestro país creció en un 23,3% frente 2021 (una subida que superó en más del doble a la media mundial), la demanda de expertos creció aún más rápido, con un aumento del 60% en el mismo periodo, según IDC.
                <br> <br>
                Es decir, aunque cada vez tengamos a más personas trabajando para reforzar nuestras defensas cibernéticas, la velocidad a la que nuestro ciberejército busca reclutar a nuevos soldados va aún más deprisa. Para el CEO de Indra, Ignacio Mataix, este desajuste representa “un excelente indicador de que el nivel de concienciación en la sociedad y en las empresas es alto y de que vamos por la buena dirección”.
                <br> <br>
                Por supuesto, ni nosotros ni nadie estamos 100% a salvo del enemigo digital. Cual buen jugador de póker, nuestro adversario oculta su mano mientras intenta descifrar la nuestra. Y por mucho que nuestras empresas hayan mejorado sus tácticas, también hace falta que usted se las aprenda. Ese es precisamente el objetivo del Día de Internet seguro: evitar que caiga en la última trampa del príncipe nigeriano. Seguro que ahora mismo los italianos estarían encantados de haber rechazado ese envite.
            </p>
    
            
             
        </div>
    </div>
    
    <div id="pie">
        <div id=centro-pie>
            <p>
                (c)Todos los derechos reservados. Diseñado por 
                <a href="https://github.com/EduardoVillacampa/eduardo.github.io" class="github"> Eduardo Villacampa</a>
            </p>
        </div>
    </div>
</body>
</html>